### ISSUE TITLE
convert KCP&L data to expected model

### ISSUE THREAD

**Issue by khambrickKCDigital** [codeforkansascity/streetlights#28]
Loading the pole data into the (json) API

**Comment by mbostwick** [comment]
Expected model is:
{	dataset:"X"
	possition:{
		lat:56.67
		long:-86.57
	},
	attributes{
		{
		name:""
		value:""
		},
		{
		name:""
		value:""
		}
	}
}

**Comment by noah-dev** [comment]
•	Northing & Easting algorithm

**Comment by mbostwick** [comment]
npm package for dealing with what @noah-dev brought up above:
https://www.npmjs.com/package/geodesy

**Comment by mbostwick** [comment]
@khambrickKCDigital I'm working on a tool for this now, however, I will need a method to chose when to load things into mongo, since we don't want to use travis for that. We will want to define when to call it. My thinking is to use a folder structure for the short term, so I can pull a folder list and only load things 1 time unless there's new data in the folders.
